# Generated by Django 5.1.7 on 2025-04-01 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci_cd.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci_cd.user')),
            ],
        ),
    ]
