# Generated by Django 5.1.7 on 2025-05-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_instructor',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
