# Generated by Django 5.1.7 on 2025-04-02 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0003_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
