# Generated by Django 5.1.7 on 2025-05-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0003_exercise_resources_exercise_solution_exercise_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
