# Generated by Django 5.1.7 on 2025-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0004_profile_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
