# Generated by Django 5.2.3 on 2025-06-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0007_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='quiz_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
