# Generated by Django 5.2.3 on 2025-06-12 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0008_progress_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ci_cd.quiz'),
        ),
    ]
