# Generated by Django 5.2.3 on 2025-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd', '0010_alter_progress_exercise_alter_progress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
